### ISSUE TITLE
Lucent Public License Version 1.02 not picked up correctly

### ISSUE THREAD

**Issue by sevki** [google/licenseclassifier#19]
[LICENSE](https://github.com/9fans/go/blob/v0.0.1/draw/LICENSE)  here is `LPL1.02` picked up here as `UNKNOWN` 
![image](https://user-images.githubusercontent.com/429977/79067182-92150f80-7cb5-11ea-89f0-dbaf191ac1e7.png)
https://pkg.go.dev/9fans.net/go@v0.0.1/draw?tab=overview

**Comment by rspier** [comment]
I'm pretty sure pkg.go.dev uses https://github.com/google/licensecheck, and not https://github.com/google/licenseclassifier.

**Comment by sevki** [comment]
there are two seperate things for this :facepalm:
