### ISSUE TITLE
match offset and extent out of range

### ISSUE THREAD

**Issue by Bobgy** [google/licenseclassifier#33]
Thank you for this amazing library! I'm amazed by its speed and accuracy, this is truly great work!

One problem I notice is that:

When I use MultipleMatch and parse the offset & extent, I found them to be inaccurate.
This is understandable if the algorithm is not perfect. However, I found cases when offset and extent is invalid for the input full text -- offset + extent is greater than full text length.

My guess is that offset and extent did not take the text normalization step into consideration: https://github.com/google/licenseclassifier/blob/bb04aff29e72e636ba260ec61150c6e15f111d7e/classifier.go#L162. So they are in fact offset and extent of the normalized text, which doesn't match the original full text.

**Comment by rspier** [comment]
IIRC, this is fixed in v2.

**Comment by Bobgy** [comment]
Thanks! I tried v2, it's awesome! The startLine and endLine exactly solves this problem.
